// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/analista-ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analista-ia">> = Specific
  const handler = {} as typeof import("../../src/app/analista-ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equipo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipo">> = Specific
  const handler = {} as typeof import("../../src/app/equipo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/estadisticas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estadisticas">> = Specific
  const handler = {} as typeof import("../../src/app/estadisticas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gastos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gastos">> = Specific
  const handler = {} as typeof import("../../src/app/gastos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ventas">> = Specific
  const handler = {} as typeof import("../../src/app/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-analyst/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-analyst/query">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-analyst/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alerts/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/alerts/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/business-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/business-snapshot">> = Specific
  const handler = {} as typeof import("../../src/app/api/business-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maintenance/clear-expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/clear-expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/maintenance/clear-expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maintenance/clear-month-sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/clear-month-sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/maintenance/clear-month-sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/maintenance/reset-test-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/reset-test-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/maintenance/reset-test-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/register-device/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/register-device">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/register-device/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parse-receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse-receipt">> = Specific
  const handler = {} as typeof import("../../src/app/api/parse-receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/professionals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/professionals">> = Specific
  const handler = {} as typeof import("../../src/app/api/professionals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
